declare const BOTBYE_MODULE_OPTIONS_DI_TOKEN = "BOTBYE_MODULE_OPTIONS_DI_TOKEN";
declare const BOTBYE_SERVICE_DI_TOKEN = "BOTBYE_SERVICE_DI_TOKEN";
declare const BOTBYE_MODULE_VALIDATE_REQUEST_DI_TOKEN = "BOTBYE_MODULE_VALIDATE_REQUEST_DI_TOKEN";
export { BOTBYE_MODULE_OPTIONS_DI_TOKEN, BOTBYE_SERVICE_DI_TOKEN, BOTBYE_MODULE_VALIDATE_REQUEST_DI_TOKEN, };
